/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeadError = IDL.Variant({ 'duplicateEmail' : IDL.Null });
export const Lead = IDL.Record({
  'country' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'targetJobRole' : IDL.Text,
});

export const idlService = IDL.Service({
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(LeadError)],
      [],
    ),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], ['query']),
  'getLeadsCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeadError = IDL.Variant({ 'duplicateEmail' : IDL.Null });
  const Lead = IDL.Record({
    'country' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'targetJobRole' : IDL.Text,
  });
  
  return IDL.Service({
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(LeadError)],
        [],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], ['query']),
    'getLeadsCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };